### PR TITLE
Clear token cache on credential update fix #26

### LINKED ISSUE #26: When changing the credentials the existing token is not removed from token cache manager
**Gally Platform version(s) affected**: 2.1.0

**Description**  
I configured a Gally user role as contributor to test the sync process. When the sync failed, I switched the user to an admin role. However, the sync still failed with an "Access denied" message.

After debugging, I discovered that the token cache manager still held an active token. Clearing the Sylius cache by deleting 'var/cache/dev' and refreshing the cache allowed me to successfully sync the data.

In the AdminGallyController code, I noticed that credentials are stored in the database, but the token cache manager remains unchanged. It seems reasonable to reset or clean the token cache manager whenever the Gally connection configuration is modified.

### PR DESCRIPTION
**Pull request by PierreGauthier**
| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

### CODE REVIEW

File: src/Controller/AdminGallyController.php [hunk 1]
```diff
@@ -45,10 +46,12 @@ public function __construct(
         protected ConfigManager $configManager,
         \IteratorAggregate $providers,
         private TranslatorInterface $translator,
+        private TokenCacheManager $tokenCacheManager,
     ) {
         /** @var ProviderInterface[] $providersArray */
         $providersArray = iterator_to_array($providers);
         $this->providers = $providersArray;
+        $this->tokenCacheManager = $tokenCacheManager;
```
Comment (botisSmile) [inline src/Controller/AdminGallyController.php]: à supprimer, je pense :smile:

**Review by botisSmile — CHANGES_REQUESTED** [review]
